"""
QRC Feature Comparison Plotting Script
======================================
Author: Marcin Plodzien

This script compares the performance of different Feature Selections (Regressor Inputs).
It loads multiple `analysis_summary_{CONFIG_NAME}.pkl` files generated by `02_analyze_qrc_ladder.py`
and aggregates them into unified plots to compare how different observables affect capacity.

Plots Generated:
----------------
1.  **Total Capacity Comparison** (`Feature_Comparison_Total_Capacity.png`):
    -   X-axis: t_evol
    -   Y-axis: Total Capacity
    -   Hue: Feature Configuration (e.g., 'ALL', 'Z_only')
    -   Fixed: Measurement Rail Config (e.g., '012' - All Rails)

2.  **Capacity Profile Comparison** (`Feature_Comparison_Profiles.png`):
    -   Grid: t_evol
    -   X-axis: Tau
    -   Y-axis: Capacity C(tau)
    -   Hue: Feature Configuration

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import importlib.util

# ==============================================================================
# CONFIGURATION
# ==============================================================================
# MANUAL_PATH = "results/QRC_TFIM_ZZ_X_N_rails_3_L_2" 
MANUAL_PATH = None

# ==============================================================================
# LOAD PATH Logic
# ==============================================================================
arg = sys.argv[1] if len(sys.argv) > 1 else (MANUAL_PATH or "01_config_qrc_ladder.py")

if arg.endswith('.py'):
    print(f"Loading Configuration from: {arg}")
    spec = importlib.util.spec_from_file_location("config", arg)
    config = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(config)
    RESULTS_DIR = config.RESULTS_DIR
else:
    RESULTS_DIR = arg

print(f"Comparison plotting targeting root: {RESULTS_DIR}")
ANALYSIS_DIR = os.path.join(RESULTS_DIR, "analysis_results")
FIGURES_DIR = os.path.join(RESULTS_DIR, "figures")

if not os.path.exists(FIGURES_DIR):
    os.makedirs(FIGURES_DIR)

# ==============================================================================
# DATA LOADING
# ==============================================================================

def find_summary_files(analysis_dir):
    """Finds all analysis_summary_*.pkl files."""
    files = []
    if not os.path.exists(analysis_dir):
        return []
    for f in os.listdir(analysis_dir):
        if f.startswith("analysis_summary_") and f.endswith(".pkl"):
             files.append(os.path.join(analysis_dir, f))
    return sorted(files)

def load_and_aggregate_summaries():
    files = find_summary_files(ANALYSIS_DIR)
    if not files:
        print("No summary files found.")
        return None
    
    dfs = []
    print(f"Found {len(files)} summary files.")
    
    for fpath in files:
        fname = os.path.basename(fpath)
        # Parse Config Name
        if fname == "analysis_summary.pkl":
            cfg_name = "Default"
        else:
            # removing prefix 'analysis_summary_' and suffix '.pkl'
            cfg_name = fname[17:-4]
            
        try:
            df = pd.read_pickle(fpath)
            if df.empty: continue
            
            # Add Feature Config Column
            df['feature_config'] = cfg_name
            dfs.append(df)
        except Exception as e:
            print(f"Error loading {fname}: {e}")
            
    if not dfs:
        return None
        
    master_df = pd.concat(dfs, ignore_index=True)
    return master_df

def standardize_columns(df):
    """Maps columns from Standalone format to Analysis format."""
    mapping = {
        'HamType': 'topology',
        'T_evol': 't_evol',
        'h_mag': 'h_mag',
        'Data': 'data_input_type',
        'State': 'input_state_type',
    }
    df = df.rename(columns=mapping)
    if 'meas_config' not in df.columns:
        df['meas_config'] = 'All'
    return df

# ==============================================================================
# PLOTTING
# ==============================================================================

def plot_total_capacity_comparison(df):
    """Comparison of Total Capacity vs Time for different Feature Sets."""
    print("Plotting Total Capacity Comparison...")
    
    # 1. Select Measurement Config
    # We want to compare Feature Sets given the "Best" Physical Measurement (e.g. All Rails '012')
    # Or we can maintain all and facet. 
    # For clarity, let's pick the one with most rails if available, or just '012'.
    
    meas_configs = df['meas_config'].unique()
    # Heuristic: Pick the one that looks like '012' or has max length
    target_meas = '012' 
    if target_meas not in meas_configs:
        # Fallback: Pick the last one (usually all)
        target_meas = meas_configs[-1]
    
    print(f"Fixing Measurement Config to: {target_meas} for feature comparison.")
    sub_df = df[df['meas_config'] == target_meas].copy()
    
    if sub_df.empty:
        print("No data after filtering.")
        return

    # Data Prep
    sub_df['t_evol'] = pd.to_numeric(sub_df['t_evol'])
    sub_df = sub_df.sort_values('t_evol')
    
    # Aggregation check
    if 'total_capacity' not in sub_df.columns:
        print("Missing total_capacity.")
        return
        
    # Plot
    plt.figure(figsize=(10, 6))
    sns.lineplot(
        data=sub_df,
        x='t_evol',
        y='total_capacity',
        hue='feature_config',
        style='feature_config',
        markers=True,
        dashes=False,
        palette='viridis'
    )
    
    plt.xscale('log')
    plt.xlabel("Evolution Time ($t_{evol}$)")
    plt.ylabel("Total Capacity $\sum C(\\tau)$")
    plt.title(f"Feature Selection Comparison\n(Measurement: {target_meas})")
    plt.grid(True, which='both', linestyle='--', alpha=0.5)
    plt.legend(title="Feature Set", bbox_to_anchor=(1.05, 1), loc='upper left')
    
    out_path = f"{FIGURES_DIR}/Feature_Comparison_Total_Capacity.png"
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    print(f"Saved {out_path}")
    plt.close()

def plot_capacity_profile_comparison(df):
    """Comparison of Capacity Profiles C(tau) for different Feature Sets."""
    print("Plotting Capacity Profile Comparison...")
    
    meas_configs = df['meas_config'].unique()
    target_meas = '012'
    if target_meas not in meas_configs:
        target_meas = meas_configs[-1]
        
    sub_df = df[df['meas_config'] == target_meas].copy()
    
    # Expand Profiles
    expanded_rows = []
    for _, row in sub_df.iterrows():
        caps = row.get('caps_per_tau')
        if isinstance(caps, (list, np.ndarray)):
            for tau, val in enumerate(caps):
                expanded_rows.append({
                    't_evol': row['t_evol'],
                    'feature_config': row['feature_config'],
                    'tau': tau,
                    'capacity': val
                })
                
    if not expanded_rows:
        return
        
    long_df = pd.DataFrame(expanded_rows)
    
    # Facet by t_evol
    g = sns.FacetGrid(long_df, col='t_evol', col_wrap=4, height=3, aspect=1.2, sharex=True, sharey=True, hue='feature_config', palette='viridis')
    g.map(sns.lineplot, 'tau', 'capacity')
    
    g.add_legend(title="Feature Set")
    g.set_axis_labels("Lag $\\tau$", "$C(\\tau)$")
    g.fig.suptitle(f"Capacity Profiles Comparison (Meas: {target_meas})", y=1.02)
    
    out_path = f"{FIGURES_DIR}/Feature_Comparison_Profiles.png"
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    print(f"Saved {out_path}")
    plt.close()

def main():
    df = load_and_aggregate_summaries()
    if df is not None:
        df = standardize_columns(df)
        plot_total_capacity_comparison(df)
        plot_capacity_profile_comparison(df)
    else:
        print("Failed to load data.")

if __name__ == "__main__":
    main()
